image: registry.cqse.eu/cqse/build-base

variables:
  GRADLE_OPTS: -Dorg.gradle.daemon=false

stages:
  - dist
  
dist:
  stage: dist
  script:
    - ./gradlew -b gradle/bootstrap.gradle bootstrap
    - rm -r .gradle gradle/.gradle .git
  artifacts:
    name: harvest-gitbridge
    paths:
      - "*"
